var gOpenCommentsFn=null;null==window.mxResourcesLoadingDone&&(window.mxResourcesLoadingDone=!1,window.mxMainPending=[]);function gOpenCommentsFunc(){null!=gOpenCommentsFn&&gOpenCommentsFn()}
function mxAddSpinner(c,a){var h=document.createElement("div");h.style.cssText=(a?"position:absolute;top:50%;left:50%;margin-left:-20px;margin-top:-20px;":"position:relative;")+"width:40px;height:40px;";c.appendChild(h);(new Spinner({lines:12,length:7,width:3,radius:6,rotate:0,color:"#000",speed:2,trail:60,shadow:!1,hwaccel:!1,className:"spinner",zIndex:999})).spin(h);return h}
MXGRAPH.fixAnchorPosition=function(){location.hash&&(null!=MXGRAPH.fixAnchorTimer&&window.clearTimeout(MXGRAPH.fixAnchorTimer),MXGRAPH.fixAnchorTimer=window.setTimeout(function(){var c=location.hash.slice(1);location.hash="";c&&(location.hash=c)},500))};
function createViewer(c,a,h){function l(k){c.innerHTML=mxUtils.htmlEntities(mxResources.get("error")+": "+k);c.style.height="24px"}function u(k,p){var b=document.createElement("div");b.style.position="absolute";b.style.overflow="hidden";b.style.left="0px";b.style.top="0px";b.style.right="0px";b.style.fontSize="14px";b.style.margin="2px";mxUtils.setOpacity(b,50);b.style.color="gray";b.style.textAlign="center";b.style.whiteSpace="nowrap";span=document.createElement("span");span.innerHTML=k;b.appendChild(span);
p.appendChild(b)}function t(k){"NO_LICENSE"==a.licenseStatus?u(mxResources.get("drawio.reader.noLicense"),k):"EVAL_LICENSE"==a.licenseStatus?u(mxResources.get("drawio.reader.evaluation"),k):"EVAL_EXPIRED"==a.licenseStatus?u(mxResources.get("drawio.reader.evaluationExpired"),k):"VERSION_MISMATCH"==a.licenseStatus?u(mxResources.get("drawio.reader.versionMismatch",["https://support.draw.io/pages/viewpage.action?pageId\x3d11829320"]),k):"USER_MISMATCH"==a.licenseStatus&&u(mxResources.get("drawio.reader.userMismatch",
["https://support.draw.io/pages/viewpage.action?pageId\x3d11829323"]),k)}function v(k){var p={};try{p=JSON.parse(k)}catch(d){try{mxUtils.parseXml(k);p.xml=k;p.revision="";var b=a.loadUrl.match(/\/([^/]+)$/);p.name=2<=b.length?decodeURIComponent(b[1]):""}catch(e){}}return p}function A(k,p){if(null!=k){var b=k.openLink;k.openLink=function(e,g){var n=window,f=e;if(null==window.DrawioProperties||null==DrawioProperties.serverConfig||"1"!=DrawioProperties.serverConfig.leaveLinkPlus)e=e.replace(/\+/g,"%2B");
f.substring(0,this.baseUrl.length)==this.baseUrl&&"#"==f.charAt(this.baseUrl.length)&&"_top"==g&&window==window.top?(f=document.createElement("a"),f.href="#"+MXGRAPH.resolvePageTargetName(p,e.split("#")[1]),f.style.display="none",c.appendChild(f),f.click(),f.parentNode.removeChild(f)):n=-1!=e.lastIndexOf("/lightbox.action")?b.apply(this,[e,"_blank"]):b.apply(this,arguments);return n};var d=k.customLinkClicked;k.customLinkClicked=function(e){var g=AJS.contextPath();if("data:confluence/id,"==e.substring(0,
19)){var n=e.substring(19),f=window.open();if(n)$.ajax({url:g+"/rest/api/content/"+encodeURIComponent(n),type:"GET",success:function(w){f.location=document.location.origin+g+w._links.webui},error:function(){f.document.writeln(mxResources.get("objectNotFound"))}});else throw Error("Empty ID");}else if("data:scrollPage,"==e.substring(0,16))try{var q=JSON.parse(Base64.decode(e.substring(16)));f=window.open();f.document.writeln(mxResources.get("connecting")+"...");$.ajax({url:g+"/rest/api/content/"+encodeURIComponent(AJS.Confluence.getContentId()),
type:"GET",success:function(w){var r=w.space.key;if(/^[ -~\t\n\r]+$/.test(q.confTitle)){var y=document.location.origin+g+"/display/"+encodeURIComponent(r)+"/"+encodeURIComponent(q.confTitle.replace(/\s/g,"+"));$.ajax({url:y,type:"GET",success:function(C){f.location=y},error:function(C){$.ajax({url:g+"/rest/api/content/"+encodeURIComponent(q.confId),type:"GET",success:function(F){f.location=document.location.origin+g+"/display/"+encodeURIComponent(r)+"/"+encodeURIComponent(F.title.replace(/\s/g,"+"))},
error:function(F){f.document.writeln(mxResources.get("pageNotFound"))}})}})}else f.location=document.location.origin+g+"/pages/viewpage.action?pageId\x3d"+encodeURIComponent(q.confId)},error:function(){f.document.writeln(mxResources.get("pageNotFound"))}});return!0}catch(w){throw Error("Unexpected Error");}else return d.apply(this,arguments)}}}function D(k,p){null!=k&&null!=p&&$(k).parents().each(function(b,d){"ui-expand"==$(d).data("macro-name")&&(p["check-visible-state"]=!1)})}if(null!=c){var B=
$.Deferred(),E=!1,m=c.parentNode;null==m||null==m.previousSibling||"drawio"!=m.getAttribute("data-macro-name")||"P"!=m.previousSibling.nodeName||0!=m.previousSibling.childNodes.length&&""!=m.previousSibling.innerHTML.trim()||m.previousSibling.appendChild(c);try{a.darkMode=h;var G=a.contextPath;editUrl=a.editUrl;Editor.initMath();GraphViewer.initCss();"undefined"!==typeof DrawioProperties&&DrawioProperties.uiConfig&&DrawioProperties.uiConfig.fontCss&&Editor.configureFontCss(DrawioProperties.uiConfig.fontCss);
a.isTemplate&&(GraphViewer.prototype.checkVisibleState=!1);if(!window.mxResourcesLoaded&&null!=a.language){window.mxResourcesLoaded=!0;var K=a.language;mxResources.isLanguageSupported(K)&&(mxClient.language=K);mxUtils.getAll([mxResources.getSpecialBundle(RESOURCE_BASE,mxClient.language)||mxResources.getDefaultBundle(RESOURCE_BASE,mxClient.language),a.resourcePath+("de"==K?"_de":"")+".txt"],function(b){for(var d=0;d<b.length;d++)mxResources.parse(b[d].getText());console.log("drawio: resources loaded");
for(window.mxResourcesLoadingDone=!0;0<window.mxMainPending.length;)console.log("drawio: main pending (2)"),window.mxMainPending.pop()()});var L=document.head.getElementsByTagName("link"),H=null;for(m=0;m<L.length;m++){var I=L[m];if("text/css"===I.getAttribute("type")&&"stylesheet"===I.getAttribute("rel")&&/.*\/styles\/custom\.css\?spaceKey=.*$/.test(I.getAttribute("href"))){H=I.outerHTML;break}}if(null!=H){var O=PrintDialog.createPrintPreview;PrintDialog.createPrintPreview=function(){var b=O.apply(this,
arguments),d=b.writeHead;b.writeHead=function(e){d.apply(this,arguments);null!=H&&e.writeln(H)};return b}}}function k(b){if("undefined"!==typeof DrawioProperties&&DrawioProperties.serverConfig&&DrawioProperties.serverConfig.linkAdjustments){if("string"===typeof DrawioProperties.serverConfig.linkAdjustments)try{for(var d=JSON.parse(mxUtils.decodeHtml(DrawioProperties.serverConfig.linkAdjustments)),e=0;e<d.length;e++)d[e].re=new RegExp(d[e].re,d[e].m);DrawioProperties.serverConfig.linkAdjustments=d}catch(n){console.log("linkAdjustments parsing error",
n)}try{if("object"===typeof DrawioProperties.serverConfig.linkAdjustments)for(d=DrawioProperties.serverConfig.linkAdjustments,e=0;e<d.length;e++){var g=d[e];b=b.replace(g.re,g.r)}}catch(n){console.log("linkAdjustments error",n)}}return b}var P=Graph.prototype.getAbsoluteUrl;Graph.prototype.getAbsoluteUrl=function(b){null!=b&&(b=k(b),"/"==b.charAt(0)&&b.substring(0,G.length)!==G&&(b=G+b));return P.apply(this,arguments)};var Q=Graph.prototype.getTooltipForCell;Graph.prototype.getTooltipForCell=function(b){var d=
null;try{return mxUtils.isNode(b.value)&&(d=b.value.getAttribute("link"),null!=d&&b.value.setAttribute("link",k(d))),Q.apply(this,arguments)}finally{null!=d&&b.value.setAttribute("link",d)}};GraphViewer.prototype.toolbarZIndex=1;var R=GraphViewer.prototype.getImageUrl,S=/^(\.\.\/)*(\.\.)?\/download\//,M=/.*com.mxgraph.confluence.plugins.diagramly:(drawio|diagramly)-editor/;GraphViewer.prototype.imageBaseUrl=document.location.origin+"/";GraphViewer.prototype.getImageUrl=function(b){return null==b?
b:"img/"==b.substring(0,4)?-1!=b.indexOf(".svg")?SVGLOADER_URL+"?url\x3d"+encodeURIComponent(b):ATLAS_RESOURCE_BASE+"/"+b:"/img/"==b.substring(0,5)?ATLAS_RESOURCE_BASE+b:S.test(b)?G+b.substring(b.indexOf("/download/")):"data:image"!=b.substring(0,10)&&M.test(b)?ATLAS_RESOURCE_BASE+b.replace(M,""):-1!=b.indexOf("/drawio/1.0/diagram/getImageAtt")?b:R.apply(this,arguments)};var T=GraphViewer.prototype.addClickHandler;GraphViewer.prototype.addClickHandler=function(b,d){var e=mxUtils.bind(this,function(){var g=
b.container.getElementsByTagName("img");if(null!=g)for(var n=0;n<g.length;n++)g[n].setAttribute("src",this.getImageUrl(g[n].getAttribute("src")))});b.model.addListener(mxEvent.CHANGE,e);e();T.apply(this,arguments)};GraphViewer.prototype.showLightbox=function(b,d,e){this.showLocalLightbox()};null!=a.width&&"fixed"!=a.width&&(c.style.width=a.width+"px");function p(b,d){if(d||window.mxResourcesLoadingDone){if(console.log("drawio: main executed?",d,E,a),!E){E=!0;GraphViewer.prototype.autoCrop=!0;var e=
mxAddSpinner(c);mxUtils.get(a.loadUrl,mxUtils.bind(this,function(g){try{e.parentNode.removeChild(e)}catch(C){console.log("drawio: viewer noise",C)}c.style.minHeight="";if(200>g.getStatus()||299<g.getStatus())l(g.getStatus());else{mxStencilRegistry.dynamicLoading=!0;t(c);g=v(g.getText());var n=mxUtils.parseXml(g.xml);a.border&&(c.style.border="1px solid #d0d0d0");var f={"toolbar-position":a.tbstyle,nav:!0,highlight:"#3b73af",border:8,"dark-mode":h};"auto"!=a.links&&(f.target=a.links);"top"==a.tbstyle&&
(f.title=(null!=a.diagramDisplayName&&0<a.diagramDisplayName.length?a.diagramDisplayName:g.name)+" ["+g.revision+"]");a.lightbox||(f.lightbox=!1);"hidden"==a.tbstyle?f.resize=!0:(f.toolbar="edit pages zoom layers tags",a.lightbox&&(f.toolbar+=" lightbox"));"fixed"==a.width?(c.style.maxWidth="",f["allow-zoom-out"]=!1):null!=a.width&&(f["allow-zoom-in"]=!0);f.zoom=isFinite(a.maxScale)?a.maxScale:1;var q=null;f["toolbar-buttons"]={edit:{title:mxResources.get("edit"),enabled:a.editable,image:MXGRAPH.editImage,
handler:function(z){-1==a.editUrl.lastIndexOf("page-id")&&(a.editUrl=a.editUrl+"\x26page\x3d"+r.currentPage);a.editUrl+="\x26directEdit\x3dtrue";MXGRAPH.openEditor(a.editUrl,z.srcElement);MXGRAPH.viewerContainer=c;MXGRAPH.readerOpts=a}}};if(null!=a.aspect&&0<a.aspect.length&&(pageAndLayers=a.aspect.split(" "),f.layerIds=1<pageAndLayers.length?pageAndLayers.slice(1):null,pageId=pageAndLayers[0],a.editUrl+="\x26page-id\x3d"+pageId,diagrams=n.documentElement.getElementsByTagName("diagram"),null!=diagrams))for(var w=
0;w<diagrams.length;w++)if(diagrams[w].getAttribute("id")==pageId){f.page=w;break}MXGRAPH.overrideGlobalVariables(a);D(c,f);var r=new GraphViewer(c,n.documentElement,f);function C(){A(r.graph,a.ceoName);MXGRAPH.overrideCellTooltips(r.graph,a.ceoName)}r.addListener("render",C);C();MXGRAPH.fixAnchorPosition();MXGRAPH.addCommentsIcon(r,c,g.attachmentId);var y=null;EditorUi.prototype.createUi=function(){};EditorUi.prototype.addTrees=function(){};EditorUi.prototype.updateActionStates=function(){};EditorUi.prototype.installNativeClipboardHandler=
function(){};EditorUi.prototype.createKeyHandler=function(){var z=new mxKeyHandler(this.editor.graph);z.bindAction=function(){};return z};EditorUi.prototype.getServiceName=function(){return"atlassian"};function F(){null==y&&(y=new EditorUi(new Editor(!1,null,null,null,!1)),y.editor.attachmentInfo={attachmentId:a.attId,revision:a.attVer},y.canComment=function(){return a.canComment});return y}function N(){null!=q?q.window.setVisible(!q.window.isVisible()):(q=new CommentsWindow(F(),document.body.offsetWidth-
380,120,300,350),q.window.setVisible(!0),q.window.getElement().style.position="fixed");q.window.getElement().style.zIndex=2E3}a.canComment&&(EditorUi.prototype.lightboxToolbarActions=[{icon:Editor.commentImage,tooltip:mxResources.get("comments"),fn:gOpenCommentsFunc}]);null!=r.graph&&null!=r.graph.model&&(r.showLocalLightbox=function(z){gOpenCommentsFn=N;MXGRAPH.overrideGlobalVariables(a);var J=GraphViewer.prototype.showLocalLightbox.call(r);A(J.editor.graph,a.ceoName);var U=J.destroy;J.destroy=function(){null!=
q&&q.window.setVisible(!1);U.apply(this,arguments)};z&&N();return J},a.canComment&&F().hasUnresolvedComments(function(z){z&&(img=document.getElementById("comments-icon-"+a.attId),img.style.display="inline")},function(){}),b.resolve(r))}}),function(){e.parentNode.removeChild(e);c.style.minHeight="";l(req.getStatus())})}}else console.log("drawio: main delayed"),window.mxMainPending.push(function(g){p(b,g)})}if(a.simpleViewer){var x=document.createElement("img");x.setAttribute("src",a.imageUrl);x.setAttribute("border",
"0");x.style.cssText="width:100%;box-sizing:border-box;padding:8px;";"fixed"==a.width&&(c.style.overflow="visible",x.style.width="");a.border&&(x.style.border="1px solid #d0d0d0");c.appendChild(x);a.lightbox&&(x.style.cursor="pointer",mxEvent.addListener(x,"click",function(){var b=mxAddSpinner(c,!0);mxUtils.get(a.loadUrl,function(d){b.parentNode.removeChild(b);if(200<=d.getStatus()&&299>=d.getStatus()){d=v(d.getText());d=mxUtils.parseXml(d.xml);var e=null,g=null;null!=a.aspect&&0<a.aspect.length&&
(e=a.aspect.split(" "),g=1<e.length?e.slice(1):null,e=e[0]);MXGRAPH.overrideGlobalVariables(a);d=new GraphViewer(null,d.documentElement,{highlight:"#3b73af",nav:!0,lightbox:!1,toolbar:"pages zoom layers tags",target:a.links,"check-visible-state":!1,pageId:e,layerIds:g});A(d.showLocalLightbox().editor.graph,a.ceoName)}},function(){b.parentNode.removeChild(b)})}));x.onload=MXGRAPH.fixAnchorPosition}else c.style.minHeight="200px",console.log("drawio: Calling main",a),p(B),setTimeout(function(){for(console.log("drawio: Pending main",
window.mxMainPending.length);0<window.mxMainPending.length;)console.log("drawio: Calling pending main"),window.mxMainPending.pop()(!0)},2E3)}catch(k){l(k.message)}return B.promise()}}
MXGRAPH.addCommentsIcon=function(c,a,h){var l=document.createElement("img");l.style.cssText="position:absolute;bottom: 5px; right: 5px;opacity: 0.25; cursor: pointer;display : none";l.id="comments-icon-"+h;l.setAttribute("title",mxResources.get("showComments"));l.src=Editor.commentImage;l.addEventListener("click",mxUtils.bind(this,function(){c.showLocalLightbox(!0)}));a.appendChild(l)};
function updateDrawioViewer(c,a,h){viewerConfig=$(this).data("viewerConfig");a==viewerConfig.diagramName&&($(this).empty(),viewerConfig.editUrl=viewerConfig.editUrl.replace(/revision=\d+/,"revision\x3d"+h),viewerConfig.loadUrl=viewerConfig.loadUrl.replace(/revision=\d+/,"revision\x3d"+h),viewerConfig.attVer=h,createViewer(this,viewerConfig,viewerConfig.darkMode))}
MXGRAPH.openEditor=function(c,a){var h=$('\x3ciframe id\x3d"drawioEditor" \x3e');h.appendTo("body");h.css({position:"fixed",width:"100%",height:"100%",top:"0px",left:"0px","border-style":"none",zIndex:9E3});h.attr("src",c);MXGRAPH.editorFrame=h;MXGRAPH.editImgEl=a;a.src=window.IMAGE_PATH+"/spin.gif";a.width=21;a.height=21};
MXGRAPH.closeEditor=function(){MXGRAPH.editorFrame.remove();MXGRAPH.editorFrame=null;MXGRAPH.viewerContainer=null;MXGRAPH.readerOpts=null;document.body.style.overflow="auto";MXGRAPH.editImgEl.src=MXGRAPH.editImage};
MXGRAPH.postSave=function(c,a,h,l,u){$(".drawio-macro").trigger("drawioViewerUpdate",[a,h]);c=new mxXmlRequest(AJS.contextPath()+"/rest/drawio/1.0/diagram/updateMacros/"+c+"/"+encodeURIComponent(a)+"/"+h+"?diagramWidth\x3d"+l+"\x26diagramHeight\x3d"+u,"","POST");c.setRequestHeaders=function(t,v){t.setRequestHeader("X-Atlassian-Token","no-check")};c.send(function(t){},function(t){console.log("There was a problem updating the drawio macro")})};
MXGRAPH.overrideCellTooltips=function(c,a){null!=c&&(oldF=c.getTooltipForCell,c.getTooltipForCell=function(h){var l=oldF.apply(this,arguments);if(null!=h.value&&null!=h.value.getAttribute&&null!=h.value.getAttribute("tooltip"))return l;l=null==l?null:MXGRAPH.resolvePageTargetName(a,l);return Graph.sanitizeHtml(l)})};
function createRemoteViewer(c,a,h,l){var u="localhost"==window.location.hostname?"test.draw.io":"ac.draw.io",t=AJS.Meta.get("user-locale");if(null!=t){var v=t.indexOf("_");0<=v&&(t=t.substring(0,v))}if(null!=c){c.style.height="200px";c.style.width="100%";v=a.diagramUrl||a.csvFileUrl?"extUrl":"GDrive"==a.service?"gdrive":"onedrive";var A="";if(l){var D=document.createElement("div");D.style.color="var(--ds-surface)";document.body.appendChild(D);A="\x26dark\x3d1\x26bkgrndClr\x3d"+encodeURIComponent(getComputedStyle(D).color);
a.darkMode=l;document.body.removeChild(D)}l=3==a.extSrvIntegType||a.diagramUrl||a.csvFileUrl?AJS.contextPath()+"/plugins/drawio/embedViewer.action?type\x3d"+v+"\x26lang\x3d"+t+A:"https://"+u+"/connect/remote_"+v+"/viewer.html?lang\x3d"+t+A;l=$('\x3ciframe style\x3d"height:100%;width:100%;border:0" src\x3d"'+l+'"\x3e');$(c).append(l);var B=l[0].contentWindow,E=mxAddSpinner(c);window.addEventListener("message",function(m){if(m.source==B)switch(m=JSON.parse(m.data),m.action){case "viewerReady":B.postMessage(JSON.stringify({action:"viewFile",
data:a}),"*");E.parentNode.removeChild(E);break;case "diagramRendered":null!=h&&(a.fileTS=m.fileTS,h(a,B));break;case "updateHeight":c.style.height=m.height+"px"}});return B}}MXGRAPH.editImage="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAVBAMAAABbObilAAAAD1BMVEUAAAAAAAAQEBBycnIgICBqwj3hAAAAAXRSTlMAQObYZgAAADlJREFUCNdjoBwoChrAmCyGggJwYWVBBSiTSVDICKFa0AEuLCiEJKyAX5gBSZgBSZgBKGwMBKQ7HAAWzQSfKKAyBgAAAABJRU5ErkJggg\x3d\x3d";